// --- PROJECT.AROID DATABASE ---
const genusDefaults = {
    'Monstera': {
        desc: "Famous for their naturally fenestrated (holey) leaves, Monsteras are tropical climbers native to the rainforests of Central and South America. They thrive in bright indirect light and love to climb moss poles.",
        propagation: ['Stem cuttings with at least one node', 'Air layering', 'Water propagation'],
        stats: { light: 'Medium to Bright (100-250 PPFD)', water: 'Let top third dry out', humidity: 'Medium (50-65%)', temp: '18-28°C', ph: '5.5 - 6.5', tox: 'Mildly toxic (Calcium oxalate)', fert: 'Bi-weekly during growth', growth: 'Fast, climbing', dorm: 'Rarely', diff: 'Medium' },
        pests: ['Thrips (highly susceptible)', 'Spider mites (in dry air)', 'Scale insects'],
        substrate: {
            organic: { name: 'Chunky Aroid Mix', mix: [{n:'Coco Coir', p:40}, {n:'Perlite/Pumice', p:30}, {n:'Orchid Bark', p:20}, {n:'Worm Castings', p:10}] },
            mineral: { name: 'Jungle Mix (Mineral)', mix: [{n:'Pumice/Lava', p:70}, {n:'Zeolite', p:20}, {n:'Fluval Stratum', p:10}] }
        }
    },
    'Philodendron': {
        desc: "One of the most diverse genera in the aroid family, Philodendrons range from velvet-leaved crawlers to massive climbers. Known for their adaptability and stunning foliage variations.",
        propagation: ['Stem cuttings (nodes)', 'Rhizome division (crawlers)'],
        stats: { light: 'Bright, indirect (150-300 PPFD)', water: 'Keep slightly moist', humidity: 'Medium to High (60-80%)', temp: '18-27°C', ph: '5.5 - 6.0', tox: 'Toxic', fert: 'Weekly (diluted)', growth: 'Medium to Fast', dorm: 'None', diff: 'Medium' },
        pests: ['Thrips', 'Mealybugs (in leaf axils)'],
        substrate: {
            organic: { name: 'Airy Philodendron Mix', mix: [{n:'Coco Coir', p:30}, {n:'Pine Bark (coarse)', p:40}, {n:'Perlite', p:20}, {n:'Charcoal', p:10}] },
            mineral: { name: 'High-CEC Mineral Pon Matrix', mix: [{n:'Pumice', p:40}, {n:'Lava Rock', p:25}, {n:'Zeolite', p:25}, {n:'Calcined Clay', p:10}] }
        }
    },
    'Anthurium': {
        desc: "Often dubbed the 'royalty' of the aroid world, Anthuriums feature incredible textures—from deep velvet to shiny, corrugated leaves. Many require high humidity environments like greenhouses or cabinets.",
        propagation: ['Stem propagation (chux)', 'Seed growing (pollination)'],
        stats: { light: 'Filtered light (100-200 PPFD)', water: 'Evenly moist, never soggy', humidity: 'Very High (>70%, Cabinet)', temp: '20-28°C', ph: '5.5 - 6.5', tox: 'Toxic', fert: 'Every 2-3 weeks (1/4 dose)', growth: 'Slow to Medium', dorm: 'Possible if cold', diff: 'Expert (Humidity-dependent)' },
        pests: ['Spider mites (classic if RH is low)', 'Fungal spots'],
        substrate: {
            organic: { name: 'Epiphyte Blend', mix: [{n:'Orchid Bark', p:50}, {n:'Sphagnum Moss', p:20}, {n:'Perlite', p:20}, {n:'Charcoal', p:10}] },
            mineral: { name: 'Cabinet Mineral Mix', mix: [{n:'Pumice', p:60}, {n:'Fluval Stratum', p:30}, {n:'Vermiculite', p:10}] }
        }
    },
    'Alocasia': {
        desc: "Also known as 'Elephant Ears', Alocasias are heavy feeders with breathtaking, sculptural leaves. They grow from corms and often go dormant in the winter.",
        propagation: ['Corm harvesting from roots', 'Rhizome division'],
        stats: { light: 'Very bright (200-400 PPFD)', water: 'Moist, root rot sensitive', humidity: 'High (60-80%)', temp: '22-28°C', ph: '5.5 - 6.5', tox: 'Toxic', fert: 'Heavy Feeder (Weekly)', growth: 'Rapid (under perfect conditions)', dorm: 'Yes (often dies back in winter)', diff: 'Expert' },
        pests: ['Spider mites (Extremely susceptible)', 'Thrips'],
        substrate: {
            organic: { name: 'Heavy-Feeder Aroid Mix', mix: [{n:'Coco Coir', p:40}, {n:'Perlite', p:30}, {n:'Pine Bark', p:20}, {n:'Worm Castings', p:10}] },
            mineral: { name: 'High-CEC Mineral Pon Matrix', mix: [{n:'Pumice', p:40}, {n:'Lava Rock', p:25}, {n:'Zeolite', p:25}, {n:'Calcined Clay', p:10}] }
        }
    },
    'Syngonium': {
        desc: "Fast-growing and highly rewarding, Syngoniums (Arrowhead Vines) are perfect for beginners. They start as bushy plants and eventually begin to vine and climb.",
        propagation: ['Stem cuttings (water or soil)'],
        stats: { light: 'Medium to Bright', water: 'Let dry slightly', humidity: 'Normal to Medium (40-60%)', temp: '18-26°C', ph: '6.0 - 6.5', tox: 'Toxic', fert: 'Bi-weekly', growth: 'Very fast', dorm: 'No', diff: 'Beginner' },
        pests: ['Spider mites', 'Aphids'],
        substrate: {
            organic: { name: 'Basic Aroid Mix', mix: [{n:'Soil', p:50}, {n:'Perlite', p:30}, {n:'Bark', p:20}] },
            mineral: { name: 'Standard Mineral', mix: [{n:'Pumice', p:50}, {n:'Lava', p:30}, {n:'Zeolite', p:20}] }
        }
    },
    'Hoya': {
        desc: "Epiphytic vines known for their waxy leaves and stunning, star-shaped, fragrant flower clusters. They require extremely airy roots and bright light to bloom.",
        propagation: ['Stem cuttings with 1-2 nodes in perlite/sphagnum'],
        stats: { light: 'Very Bright, some direct sun ok', water: 'Let dry out completely', humidity: 'Normal (40-60%)', temp: '18-30°C', ph: '6.0 - 7.0', tox: 'Non-toxic', fert: 'Monthly (Orchid fertilizer)', growth: 'Slow (in bursts)', dorm: 'Yes (cooler winter rest)', diff: 'Advanced' },
        pests: ['Mealybugs (frequent)', 'Scale insects'],
        substrate: {
            organic: { name: 'Hoya Epiphyte Mix', mix: [{n:'Fine Pine Bark', p:50}, {n:'Perlite', p:30}, {n:'Coco Fiber', p:20}] },
            mineral: { name: 'Lechuza / Pon Mix', mix: [{n:'Pumice', p:40}, {n:'Lava', p:40}, {n:'Zeolite', p:20}] }
        }
    },
    'Epipremnum': {
        desc: "The ultimate survivor plant. Epipremnum (Pothos) species are incredibly resilient trailing vines that can adapt to almost any indoor environment.",
        propagation: ['Single-node stem cuttings in water'],
        stats: { light: 'Medium to Bright', water: 'Let dry well before watering', humidity: 'Tolerant (40-60%)', temp: '15-30°C', ph: '6.0 - 6.5', tox: 'Toxic', fert: 'Every 2-4 weeks', growth: 'Very fast, trailing/climbing', dorm: 'No', diff: 'Beginner' },
        pests: ['Thrips', 'Mealybugs'],
        substrate: {
            organic: { name: 'Airy Houseplant Mix', mix: [{n:'Quality Soil', p:60}, {n:'Perlite', p:30}, {n:'Pine Bark', p:10}] },
            mineral: { name: 'Hydro/Pon Standard', mix: [{n:'Pumice', p:50}, {n:'Lava', p:30}, {n:'Zeolite', p:20}] }
        }
    },
    'Ficus': {
        desc: "From the popular Rubber Tree to the Fiddle Leaf Fig, Ficus are majestic indoor trees. They hate being moved and drop leaves if exposed to cold drafts.",
        propagation: ['Stem cuttings', 'Air layering'],
        stats: { light: 'Very Bright, tolerates morning sun', water: 'Moderate, let top dry slightly', humidity: 'Medium (50-60%)', temp: '18-25°C', ph: '6.0 - 6.5', tox: 'Toxic (Milky sap)', fert: 'Bi-weekly (Spring-Fall)', growth: 'Medium', dorm: 'Winter rest', diff: 'Advanced' },
        pests: ['Spider mites', 'Scale insects'],
        substrate: {
            organic: { name: 'Ficus Mix', mix: [{n:'Houseplant Soil', p:50}, {n:'Perlite', p:30}, {n:'Pumice', p:20}] },
            mineral: { name: 'Mineral Mix', mix: [{n:'Pumice', p:50}, {n:'Lava', p:30}, {n:'Zeolite', p:20}] }
        }
    },
    'Dracaena': {
        desc: "Robust, palm-like plants known for their sword-shaped leaves and extreme drought tolerance. Often used as striking architectural floor plants.",
        propagation: ['Stem cuttings (water or soil)'],
        stats: { light: 'Medium to Bright, indirect', water: 'Let dry completely', humidity: 'Normal (40-60%)', temp: '18-28°C', ph: '6.0 - 6.5', tox: 'Toxic to pets', fert: 'Monthly (diluted)', growth: 'Slow to Medium', dorm: 'No', diff: 'Beginner' },
        pests: ['Spider mites', 'Mealybugs'],
        substrate: {
            organic: { name: 'Well-draining Mix', mix: [{n:'Soil', p:50}, {n:'Perlite', p:30}, {n:'Sand', p:20}] },
            mineral: { name: 'Standard Mineral', mix: [{n:'Pumice', p:50}, {n:'Lava', p:30}, {n:'Zeolite', p:20}] }
        }
    },
    'Zamioculcas': {
        desc: "The ZZ Plant is virtually indestructible. It stores water in its thick rhizomes, making it highly drought-tolerant and capable of surviving in low-light conditions.",
        propagation: ['Leaf cuttings (slow)', 'Rhizome division'],
        stats: { light: 'Shade tolerant to Bright', water: 'Very rare, let dry completely', humidity: 'Tolerant', temp: '18-28°C', ph: '6.0 - 7.0', tox: 'Toxic', fert: 'Every 6-8 weeks', growth: 'Slow', dorm: 'No', diff: 'Beginner' },
        pests: ['Nearly immune'],
        substrate: {
            organic: { name: 'Succulent Mix', mix: [{n:'Cactus Soil', p:60}, {n:'Pumice', p:40}] },
            mineral: { name: 'Pon Standard', mix: [{n:'Pumice', p:40}, {n:'Lava', p:40}, {n:'Zeolite', p:20}] }
        }
    },
    'Strelitzia': {
        desc: "The Bird of Paradise brings instant tropical flair to any room. These massive, light-hungry plants feature huge paddle-shaped leaves.",
        propagation: ['Root/Rhizome division'],
        stats: { light: 'Full sun', water: 'Generous', humidity: 'Medium (50-65%)', temp: '15-30°C', ph: '5.5 - 6.5', tox: 'Mildly toxic', fert: 'Weekly in summer', growth: 'Medium to Fast', dorm: 'Winter rest', diff: 'Advanced' },
        pests: ['Scale insects', 'Spider mites'],
        substrate: {
            organic: { name: 'Heavy-Feeder Mix', mix: [{n:'Soil', p:50}, {n:'Clay pebbles', p:30}, {n:'Sand', p:20}] },
            mineral: { name: 'Coarse Mineral', mix: [{n:'Lava', p:50}, {n:'Pumice', p:40}, {n:'Zeolite', p:10}] }
        }
    },
    'Calathea': {
        desc: "Known for their incredibly patterned foliage that moves up and down with the sun (nyctinasty). They are notoriously dramatic.",
        propagation: ['Rhizome division'],
        stats: { light: 'Shady to Partial Shade', water: 'Constantly slightly moist, distilled water', humidity: 'Very High (>65%)', temp: '18-25°C', ph: '6.0', tox: 'Non-toxic', fert: 'Monthly, diluted', growth: 'Medium', dorm: 'No', diff: 'Expert' },
        pests: ['Spider mites', 'Thrips'],
        substrate: {
            organic: { name: 'Marantaceae Mix', mix: [{n:'Coco Coir', p:50}, {n:'Perlite', p:30}, {n:'Sphagnum', p:20}] },
            mineral: { name: 'Semi-Mineral', mix: [{n:'Pumice', p:60}, {n:'Fluval', p:40}] }
        }
    },
    'Rhaphidophora': {
        desc: "Fast-growing climbing aroids from Southeast Asia. Often confused with Monstera, they possess naturally split leaves but remain much smaller and more compact.",
        propagation: ['Stem cuttings (nodes)'],
        stats: { light: 'Medium to Bright', water: 'Let dry slightly', humidity: 'Normal (40-60%)', temp: '18-27°C', ph: '6.0 - 6.5', tox: 'Toxic', fert: 'Bi-weekly', growth: 'Very Fast', dorm: 'No', diff: 'Beginner' },
        pests: ['Thrips', 'Spider mites'],
        substrate: {
            organic: { name: 'Airy Aroid Mix', mix: [{n:'Coco Coir', p:40}, {n:'Perlite', p:40}, {n:'Bark', p:20}] },
            mineral: { name: 'Standard Mineral', mix: [{n:'Pumice', p:50}, {n:'Lava', p:30}, {n:'Zeolite', p:20}] }
        }
    },
    'Scindapsus': {
        desc: "Trailing or climbing aroids famous for their thick, slightly rigid leaves covered in ghostly, shimmering silver variegation.",
        propagation: ['Single-node cuttings'],
        stats: { light: 'Low to Bright indirect', water: 'Let dry until leaves curl slightly', humidity: 'Medium (50-60%)', temp: '18-28°C', ph: '6.0 - 6.5', tox: 'Toxic', fert: 'Monthly', growth: 'Medium to Slow', dorm: 'No', diff: 'Beginner+' },
        pests: ['Scale', 'Spider mites'],
        substrate: {
            organic: { name: 'Chunky Mix', mix: [{n:'Quality Soil', p:40}, {n:'Orchid Bark', p:30}, {n:'Perlite', p:30}] },
            mineral: { name: 'Mineral Blend', mix: [{n:'Pumice', p:40}, {n:'Lava', p:40}, {n:'Zeolite', p:20}] }
        }
    },
    'Aglaonema': {
        desc: "The Chinese Evergreen. Exceptionally hardy terrestrial aroids that come in a dizzying array of vivid colors and patterns, capable of surviving very low light.",
        propagation: ['Root division', 'Stem cuttings'],
        stats: { light: 'Low to Bright', water: 'Let top half dry out', humidity: 'Normal', temp: '18-25°C', ph: '5.5 - 6.5', tox: 'Toxic', fert: 'Monthly', growth: 'Slow', dorm: 'Rarely', diff: 'Beginner' },
        pests: ['Mealybugs', 'Spider mites'],
        substrate: {
            organic: { name: 'Houseplant Mix', mix: [{n:'Soil', p:60}, {n:'Perlite', p:40}] },
            mineral: { name: 'Semi-Hydro', mix: [{n:'Pumice', p:60}, {n:'Zeolite', p:40}] }
        }
    },
    'Spathiphyllum': {
        desc: "The Peace Lily. Known for its elegant white spathe 'flowers' and extreme dramatic wilting when thirsty. An excellent beginner plant that communicates its needs clearly.",
        propagation: ['Root division'],
        stats: { light: 'Low to Medium', water: 'Keep consistently moist', humidity: 'Medium to High', temp: '18-26°C', ph: '5.8 - 6.5', tox: 'Toxic', fert: 'Monthly', growth: 'Fast', dorm: 'No', diff: 'Beginner' },
        pests: ['Fungus gnats (due to wet soil)'],
        substrate: {
            organic: { name: 'Moisture Retentive Mix', mix: [{n:'Peat/Coir', p:60}, {n:'Perlite', p:30}, {n:'Worm Castings', p:10}] },
            mineral: { name: 'Lechuza Pon', mix: [{n:'Pumice', p:40}, {n:'Lava', p:40}, {n:'Zeolite', p:20}] }
        }
    },
    'Other': {
        desc: "Unique and specialized botanical wonders that don't fit into the main categories.",
        propagation: ['Varies by species'],
        stats: { light: 'Varies', water: 'Varies', humidity: 'Medium to High', temp: '20-25°C', ph: '6.0', tox: 'Varies', fert: 'Bi-weekly', growth: 'Medium', dorm: 'Varies', diff: 'Advanced' },
        pests: ['Spider mites', 'Fungus gnats'],
        substrate: {
            organic: { name: 'Premium Mix', mix: [{n:'Soil', p:60}, {n:'Perlite', p:40}] },
            mineral: { name: 'Mineral', mix: [{n:'Pumice', p:50}, {n:'Lava', p:50}] }
        }
    }
};

const plantsData = [
    { id: 1, g: 'Monstera', n: 'Monstera deliciosa', feat: 'The iconic Swiss Cheese Plant. Originating from the tropical rainforests of southern Mexico and Panama, this magnificent hemiepiphyte is a staple of any serious collection. In its natural habitat, it exhibits positive phototropism, crawling across the dark forest floor before latching onto massive canopy trees. Its characteristic fenestrations are a brilliant evolutionary adaptation, allowing hurricane-force winds to pass through without tearing the leaves, while also letting dappled light reach lower foliage. Fenestrations evolve as the plant matures.', lvl: 'Beginner', origin: 'Central America', habitat: 'Tropical Rainforest', trivia: 'Fenestrations evolve as the plant matures.' },
    { id: 2, g: 'Monstera', n: 'Monstera deliciosa \'Albo Variegata\'', feat: 'A rare and highly coveted spontaneous genetic mutation of the classic Deliciosa, the Albo is prized for its stark, chimeric white sectors. Because the achlorophyllous (white) sections lack the ability to photosynthesize, the plant grows significantly slower and is highly sensitive to light stress. Each leaf is a unique natural painting resulting from meristematic tissue instability, making it a high-stakes favorite for advanced collectors who can manage its propensity for necrotic spotting in low humidity. Variegation is unstable and can revert.', lvl: 'Expert', origin: 'Genetic Mutation', habitat: 'Cultivation', trivia: 'Variegation is unstable and can revert.' },
    { id: 3, g: 'Monstera', n: 'Monstera \'Thai Constellation\'', feat: 'Unlike the naturally occurring Albo, the Thai Constellation was specifically engineered via tissue culture in a laboratory in Thailand. Its starry-sky pattern of creamy yellow speckles and large macroscopic sectors is genetically stable, meaning it will rarely revert to full green. It is a robust grower that brings a piece of a distant galaxy into the living room, standing as a testament to modern botanical micropropagation techniques. Genetically stable variegation.', lvl: 'Advanced', origin: 'Thailand', habitat: 'Laboratory Origin', trivia: 'Genetically stable variegation.' },
    { id: 4, g: 'Monstera', n: 'Monstera deliciosa \'Aurea\'', feat: 'Also known as Marmorata, this rare cultivar features stunning golden-yellow (aurea) variegation. The variegation occurs due to a partial lack of chlorophyll combined with the presence of carotenoids. The yellow parts often emerge as a lime green before hardening off into a brilliant gold under high light intensity. It requires precisely calibrated light gradients to maintain its vibrant, sunny coloration without burning. Yellow variegation hardens from lime green.', lvl: 'Expert', origin: 'Mutation', habitat: 'Rainforest Understory', trivia: 'Yellow variegation hardens from lime green.' },
    { id: 5, g: 'Monstera', n: 'Monstera adansonii \'Archipelago\'', feat: 'A highly sought-after variegated form of the Monkey Mask. Its leaves are smaller and more delicate than the Deliciosa, but the high-contrast white marbling makes it a true botanical showstopper. It exhibits strong apical dominance and will produce increasingly large, heavily fenestrated leaves if provided with a sphagnum moss pole to stimulate aerial root attachment. Highly unstable white variegation.', lvl: 'Expert', origin: 'Indonesian Mutation', habitat: 'Tropical Jungle', trivia: 'Highly unstable white variegation.' },
    { id: 6, g: 'Monstera', n: 'Monstera adansonii \'Mint\'', feat: 'The Mint Adansonii features a delicate, misty green marbling, a unique form of stable chlorophyll variation where the cells possess a reduced number of chloroplasts rather than lacking them entirely. This gives the appearance that a fine, mint-colored powder has been dusted over its fenestrated leaves. It requires high ambient humidity (70%+) and precise care to maintain the clarity of its mutation. Mint color is a form of stable chlorophyll variation.', lvl: 'Expert', origin: 'Indonesia', habitat: 'Cloud Forest', trivia: 'Mint color is a form of stable chlorophyll variation.' },
    { id: 7, g: 'Monstera', n: 'Monstera obliqua \'Peru\'', feat: 'Often considered the \'Holy Grail\' of aroids. A true Monstera obliqua \'Peru\' is physiologically fascinating: its leaves consist of up to 90% empty space, looking like a delicate skeletal structure. Evolving in the extremely humid Amazonian understory, it grows incredibly slowly and requires near-perfect high-humidity conditions (frequently cultivated in terrariums) to prevent the fragile leaf margins from desiccating. 90% of the leaf surface consists of holes.', lvl: 'Expert', origin: 'Amazon Basin', habitat: 'Ultra-humid jungle floor', trivia: '90% of the leaf surface consists of holes.' },
    { id: 8, g: 'Monstera', n: 'Monstera esqueleto', feat: 'Translating to \'skeleton\', the Esqueleto features massive, dramatic fenestrations that stretch from the midrib to the leaf margin. Native to the cloud forests of Costa Rica, it can reach incredible sizes when given a proper epiphytic climbing structure. Its foliage looks like a window into the jungle canopy, capturing the essence of the rainforest\'s fight for light. Leaves can reach 2 feet in length.', lvl: 'Advanced', origin: 'Costa Rica', habitat: 'Mountain Cloud Forests', trivia: 'Leaves can reach 2 feet in length.' },
    { id: 9, g: 'Monstera', n: 'Monstera subpinnata', feat: 'Diverging completely from the typical fenestrated Monstera morphology, the Subpinnata features deeply lobed, pinnate leaves that do not form enclosed holes. Native to the wet tropical canopies of Ecuador, it is a graceful, structural climber that evolved these fern-like fronds to maximize surface area for photosynthesis in highly shaded environments. Pinnate leaves are rare for the genus.', lvl: 'Advanced', origin: 'Ecuador', habitat: 'Wet Tropical Canopy', trivia: 'Pinnate leaves are rare for the genus.' },
    { id: 10, g: 'Philodendron', n: 'Philodendron \'Pink Princess\'', feat: 'A vintage 1970s hybrid that splashes vibrant bubblegum pink across its foliage. As a self-heading climber, it tells a story of unpredictability—every leaf emerges from the cataphyll as a new reveal of color. The pink variegation is a result of anthocyanin pigments overriding chlorophyll in mutated cells. Strategic pruning to the last highly variegated node is often necessary to prevent reversion. Pruning helps maintain pink color.', lvl: 'Advanced', origin: '70s Hybrid', habitat: 'Indoor Cultivation', trivia: 'Pruning helps maintain pink color.' },
    { id: 11, g: 'Philodendron', n: 'Philodendron \'White Knight\'', feat: 'A breathtaking variegated jewel. Its velvety, dark emerald leaves are splashed with stark, pure white sectors. Because the white tissue is highly fragile and lacks chloroplasts, it is incredibly prone to browning if humidity drops. It is also a prime target for spider mites, requiring constant vigilance. Highly susceptible to pests.', lvl: 'Expert', origin: 'Mutation', habitat: 'Tropical Jungle', trivia: 'Highly susceptible to pests.' },
    { id: 33, g: 'Alocasia', n: 'Alocasia \'Jacklyn\'', feat: 'A prehistoric-looking, recently discovered specimen from the island of Sulawesi, Indonesia. Its deeply lobed, highly textured (pubescent) leaves feature dark green tissue and even darker, almost black venation. It grows in the tropical jungle floor and is a symbol of Southeast Asia\'s incredible, untapped biodiversity. Recently discovered species.', lvl: 'Expert', origin: 'Sulawesi, Indonesia', habitat: 'Tropical Jungle Floor', trivia: 'Recently discovered species.' },
    { id: 34, g: 'Alocasia', n: 'Alocasia azlanii', feat: 'The Jewel Alocasia. Its incredibly dark leaves flash with iridescent purple, copper, and red tones when they catch the light, thanks to specialized epidermal cells. A rare and stunning gem from the shaded rainforest understories of Borneo, it requires extremely high humidity to maintain its metallic sheen. Iridescent red veins.', lvl: 'Expert', origin: 'Borneo', habitat: 'Shaded Rainforest Understory', trivia: 'Iridescent red veins.' },
    { id: 35, g: 'Alocasia', n: 'Alocasia \'Dragon Scale\'', feat: 'The leaves of the Dragon Scale are incredibly thick, coriaceous, and deeply textured, closely resembling the scales of a mythical creature. Originating from the limestone forest floors of Borneo, this compact jewel alocasia loves humidity but requires highly aerated, calcium-rich substrate to thrive. Leaves feel like rigid plastic.', lvl: 'Advanced', origin: 'Borneo', habitat: 'Limestone Forest floor', trivia: 'Leaves feel like rigid plastic.' },
    { id: 36, g: 'Alocasia', n: 'Alocasia \'Silver Dragon\'', feat: 'A ghostly, spectral version of the Dragon Scale. Its pale, shimmering silver leaves are heavily contrasted by deep, sunken, nearly black veins. A true standout in any jewel alocasia collection, it utilizes its pale coloration to reflect excess light and regulate leaf temperature in the humid understory. Ghostly silver leaf sheen.', lvl: 'Advanced', origin: 'Borneo', habitat: 'Humid Understory', trivia: 'Ghostly silver leaf sheen.' },
    { id: 37, g: 'Alocasia', n: 'Alocasia cuprea \'Red Secret\'', feat: 'The Cuprea looks as though it was hammered from solid sheets of copper. Its leaves possess an intense metallic sheen and a deep, blood-red underside. The red undersides (abaxial surface) reflect light back up through the leaf tissue, maximizing photosynthesis in the extremely dark shaded environments of Borneo. Intense metallic copper sheen.', lvl: 'Advanced', origin: 'Borneo', habitat: 'Shaded tropical forests', trivia: 'Intense metallic copper sheen.' },
    { id: 38, g: 'Alocasia', n: 'Alocasia black velvet', feat: 'Compact and deeply elegant, the Black Velvet features nearly black, highly velvety leaves with stark, contrasting white veins. The velvety surface consists of specialized conical cells that trap and focus light directly into the chloroplasts, giving the leaf its light-absorbing, pitch-black appearance. Leaves absorb light, appearing black.', lvl: 'Advanced', origin: 'Southeast Asia', habitat: 'Terrestrial forest floor', trivia: 'Leaves absorb light, appearing black.' },
    { id: 39, g: 'Alocasia', n: 'Alocasia zebrina', feat: 'Famous for its striking, highly decorative petioles that feature a distinct, repeating zebra-stripe pattern. It produces large, sharply arrowhead-shaped leaves that act as massive solar panels. Native to the Philippines, it requires exceptionally bright light to prevent its long, decorative stems from drooping. Stems are more decorative than leaves.', lvl: 'Advanced', origin: 'Philippines', habitat: 'Tropical Clearings', trivia: 'Stems are more decorative than leaves.' },
    { id: 40, g: 'Alocasia', n: 'Alocasia macrorrhizos \'Variegata\'', feat: 'The giant variegated Alocasia. It can grow massive, elephant-ear leaves larger than a human, wildly splashed with massive blocks of white and cream. It is a heavy, voracious feeder and a rapid grower. The white variegation is highly unstable, requiring careful pruning to maintain its chimeric beauty. Can grow to massive proportions.', lvl: 'Expert', origin: 'Southeast Asia', habitat: 'Open tropical forests', trivia: 'Can grow to massive proportions.' },
    { id: 41, g: 'Syngonium', n: 'Syngonium \'Albo Variegata\'', feat: 'A vigorous, highly rewarding variegated climber. It is widely considered one of the easiest aroids to maintain stark white variegation on. It aggressively climbs and produces arrow-shaped leaves with large white blocks and speckles, transforming into a massive, multi-lobed plant in its mature, climbing form. Very easy to propagate.', lvl: 'Beginner+', origin: 'Central America', habitat: 'Vigorous Jungle Climber', trivia: 'Very easy to propagate.' },
    { id: 42, g: 'Syngonium', n: 'Syngonium \'Milk Confetti\'', feat: 'A pastel botanical dream. Its pale, milky-green leaves are heavily speckled with bright, bubblegum-pink dots that look like scattered confetti. A highly engineered, cute, and relatively easy-to-grow cultivar that brings a soft, unnatural color palette to any serious plant collection. Pink speckles are highly sought after.', lvl: 'Advanced', origin: 'Cultivar', habitat: 'Bright Indirect Light', trivia: 'Pink speckles are highly sought after.' },
    { id: 43, g: 'Syngonium', n: 'Syngonium \'Red Spot Tricolor\'', feat: 'A spectacular, highly unstable tri-color mutation featuring deep green, stark white, and vibrant pink on every single leaf. It is a slow climber that requires incredibly precise, high-intensity lighting to maintain its delicate color balance without causing the white sectors to burn. Three-color mutation is rare.', lvl: 'Expert', origin: 'Mutation', habitat: 'Cultivation', trivia: 'Three-color mutation is rare.' },
    { id: 44, g: 'Syngonium', n: 'Syngonium \'Pink Splash\'', feat: 'Features deep, dark green leaves heavily splashed with brilliant neon pink. It is a fast-growing, highly aggressive climber that adds a pop of artificial-looking, intense color to any plant shelf. The pink splashes are caused by localized anthocyanin overproduction in the leaf tissue. Vibrant pink contrast.', lvl: 'Advanced', origin: 'Cultivar', habitat: 'Tropical Jungle (Species)', trivia: 'Vibrant pink contrast.' },
    { id: 45, g: 'Syngonium', n: 'Syngonium \'Mojito\'', feat: 'The Mojito features a highly refined, fine minty marbling over dark green leaves. It is an elegant cultivar that looks exactly like a freshly muddled drink. The highly scattered, mosaic-like variegation is relatively stable and responds beautifully to bright, indirect sunlight. Minty marbled variegation.', lvl: 'Advanced', origin: 'Cultivar', habitat: 'Bright Indirect Light', trivia: 'Minty marbled variegation.' },
    { id: 46, g: 'Hoya', n: 'Hoya carnosa \'Compacta Regalis\'', feat: 'The variegated Hindu Rope. Its tightly curled, heavily twisted and contorted leaves are beautifully edged with white and pink margins. It is an exceptionally slow grower that occasionally produces stunning, highly fragrant, star-shaped umbels (flower clusters) that drip with sweet nectar. Curled leaves trap dust; clean regularly.', lvl: 'Advanced', origin: 'East Asia', habitat: 'Epiphytic Vine', trivia: 'Curled leaves trap dust; clean regularly.' },
    { id: 47, g: 'Hoya', n: 'Hoya australis \'Lisa\'', feat: 'A beautiful, vigorous Hoya exhibiting reverse variegation, with yellow and pink coloration in the leaf center rather than the margins. New growth emerges a brilliant, shocking red before hardening off into sunset tones. Native to the coastal forests of Australia, it loves high light. New growth is bright red/pink.', lvl: 'Advanced', origin: 'Australia', habitat: 'Coastal Forest Epiphyte', trivia: 'New growth is bright red/pink.' },
    { id: 48, g: 'Hoya', n: 'Hoya callistophylla (Non-Aroid)', feat: 'Grown entirely for its incredible, intricate leaf venation. The dark green veins look as though they were meticulously drawn onto the light green leaves with a fine-tip pen. Native to the Bornean canopy, it requires extremely airy, epiphytic substrate to prevent root rot. One of the best foliage Hoyas.', lvl: 'Advanced', origin: 'Borneo', habitat: 'Tropical Canopy', trivia: 'One of the best foliage Hoyas.' },
    { id: 49, g: 'Hoya', n: 'Hoya kerrii \'Variegata\'', feat: 'The sweetheart Hoya. Its thick, rigid, perfectly heart-shaped leaves are beautifully bordered with creamy yellow margins. It is a slow-growing epiphytic vine that is famously (and often frustratingly) gifted as a single, rooted \'zombie leaf\' that may never produce a climbing vine. Single leaves often don\'t grow into vines.', lvl: 'Advanced', origin: 'Southeast Asia', habitat: 'Epiphytic Climber', trivia: 'Single leaves often don\'t grow into vines.' },
    { id: 50, g: 'Hoya', n: 'Hoya polyneura \'Albomarginata\'', feat: 'The \'Fishtail Hoya\'. Its deeply veined leaves are sharply shaped like the tails of fish, featuring striking white borders in this incredibly rare Albomarginata variety. Endemic to the Himalayas, it is a strict cool-grower that demands lower temperatures and high humidity to survive. Fishtail-shaped foliage.', lvl: 'Expert', origin: 'Himalayas / SW China', habitat: 'Cool Mountain Forests', trivia: 'Fishtail-shaped foliage.' },
    { id: 51, g: 'Hoya', n: 'Hoya wayetii \'Variegata\'', feat: 'Features long, narrow, canoe-shaped leaves with crisp white edges. When exposed to high light intensities, the edges undergo \'sun-stressing\', turning a beautiful, deep pink or purple color as the plant produces anthocyanins to protect its chlorophyll from UV damage. Sun-stresses into pink tones.', lvl: 'Advanced', origin: 'Philippines', habitat: 'Trailing Epiphyte', trivia: 'Sun-stresses into pink tones.' },
    { id: 52, g: 'Calathea', n: 'Calathea \'White Fusion\'', feat: 'The ultimate \'diva\' of the botanical world. Its leaves look like incredibly detailed watercolor paintings with white, green, and pale purple swirls. To prevent the delicate white tissue from immediately turning brown and crisp, it demands pure distilled water and constant, greenhouse-level humidity. Demands distilled water.', lvl: 'Expert', origin: 'Cultivar', habitat: 'Shaded Rainforest Floor', trivia: 'Demands distilled water.' },
    { id: 57, g: 'Calathea', n: 'Calathea orbifolia', feat: 'Features massive, nearly perfectly round leaves adorned with elegant, sweeping silver stripes. It looks like a carefully engineered designer plant. Native to Bolivia, it requires highly consistent, even moisture and distilled water to prevent its massive leaves from developing brown, necrotic edges. Massive circular leaves.', lvl: 'Advanced', origin: 'Bolivia', habitat: 'Shaded forest floor', trivia: 'Massive circular leaves.' },
    { id: 58, g: 'Calathea', n: 'Calathea makoyana', feat: 'The Peacock Plant. Its paper-thin leaves feature incredibly intricate, feather-like patterns that are perfectly mirrored in a deep purple on the leaf\'s underside. It is highly reactive to light, aggressively moving its leaves up and down daily to track the sun and conserve moisture. Known as the Peacock Plant.', lvl: 'Advanced', origin: 'Brazil', habitat: 'Humid Understory', trivia: 'Known as the Peacock Plant.' },
    { id: 55, g: 'Epipremnum', n: 'Epipremnum pinnatum \'Albo Variegata\'', feat: 'A fast, aggressive climber that develops massive, dramatic fenestrations (splits) as it matures. It features stunning, bright white sectors and is much more rewarding and dramatic to grow on a moss pole than the standard Pothos, eventually morphing into a completely different-looking mature plant. Fenestrates when climbing.', lvl: 'Advanced', origin: 'Southeast Asia', habitat: 'Aggressive Jungle Climber', trivia: 'Fenestrates when climbing.' },
    { id: 59, g: 'Epipremnum', n: 'Epipremnum aureum', feat: 'The classic Golden Pothos. Virtually indestructible, highly adaptable, and capable of surviving in windowless, dark offices. Native to French Polynesia, it is an aggressive climber that can completely take over native trees if released into the wild. A staple for any beginner. Can survive in very low light.', lvl: 'Beginner', origin: 'French Polynesia', habitat: 'Highly Adaptable', trivia: 'Can survive in very low light.' },
    { id: 60, g: 'Epipremnum', n: 'Epipremnum aureum \'Marble Queen\'', feat: 'A highly variegated, classic Pothos heavily marbled with pure white. Because it possesses significantly less chlorophyll than the Golden Pothos, it grows noticeably slower and requires much brighter light to thrive and prevent its elegant white sections from reverting to green. Needs more light than Golden Pothos.', lvl: 'Beginner+', origin: 'Cultivar', habitat: 'Indoor Cultivation', trivia: 'Needs more light than Golden Pothos.' },
    { id: 61, g: 'Epipremnum', n: 'Epipremnum aureum \'Neon\'', feat: 'Features luminous, bright chartreuse-yellow leaves that literally glow in any room. It is just as resilient and easy to care for as the standard Pothos, but adds a massive pop of bright, almost unnatural neon color. High light keeps the neon color vibrant; low light turns it dull green. Neon yellow foliage.', lvl: 'Beginner', origin: 'Cultivar', habitat: 'Indoor Cultivation', trivia: 'Neon yellow foliage.' },
    { id: 62, g: 'Ficus', n: 'Ficus elastica', feat: 'The robust, highly architectural Rubber Tree. Native to Southeast Asia, it grows into massive, sprawling banyan-like trees in the wild. Its thick, leathery leaves store immense amounts of water, making it highly resilient. Its sap contains natural latex, which is highly toxic to pets. Sap contains natural latex.', lvl: 'Beginner+', origin: 'Southeast Asia', habitat: 'Lowland Rainforest', trivia: 'Sap contains natural latex.' },
    { id: 63, g: 'Ficus', n: 'Ficus elastica \'Tineke\'', feat: 'A stunningly variegated Rubber Tree featuring a watercolor-like camouflage pattern of sage green, cream, and pink. It is a striking indoor tree that absolutely loves bright light. The pink tones become significantly more pronounced and vibrant when exposed to direct morning sunlight. Pink tones appear with more light.', lvl: 'Advanced', origin: 'Cultivar', habitat: 'Bright Indoor Spaces', trivia: 'Pink tones appear with more light.' },
    { id: 64, g: 'Ficus', n: 'Ficus lyrata', feat: 'The famous Fiddle Leaf Fig. Its massive, highly textured, violin-shaped leaves have made it an absolute icon in modern interior design. Native to West Africa, it is notoriously finicky, dropping its leaves dramatically if exposed to cold drafts, erratic watering, or if moved from its favorite spot. Interior design staple.', lvl: 'Advanced', origin: 'West Africa', habitat: 'Lowland Rainforest', trivia: 'Interior design staple.' },
    { id: 69, g: 'Dracaena', n: 'Dracaena marginata', feat: 'Known for its thin, spiky, red-edged leaves that grow in bursts on top of slender, architectural canes. An absolute survivor from Madagascar, it can handle extreme drought and incredibly low light with ease, making it a perfect, low-maintenance architectural floor plant for modern spaces. Extremely drought tolerant.', lvl: 'Beginner', origin: 'Madagascar', habitat: 'Dry Scrubland', trivia: 'Extremely drought tolerant.' },
    { id: 70, g: 'Dracaena', n: 'Dracaena fragrans', feat: 'The classic Corn Plant. It features broad, sweeping leaves with a lighter central stripe and can eventually grow into a large, highly robust indoor tree. It is extremely hardy, highly forgiving of neglect, and perfect for adding significant greenery to low-maintenance spaces. Known for its corn-like foliage.', lvl: 'Beginner', origin: 'Tropical Africa', habitat: 'Upland Forests', trivia: 'Known for its corn-like foliage.' },
    { id: 65, g: 'Zamioculcas', n: 'Zamioculcas zamiifolia', feat: 'The absolutely indestructible ZZ Plant. Having evolved in the brutal, dry rocky regions of Eastern Africa, it stores massive amounts of water in thick, potato-like underground rhizomes. It is virtually immune to all pests and can survive for months without water in near-total darkness. Virtually immune to pests.', lvl: 'Beginner', origin: 'Eastern Africa', habitat: 'Dry rocky forests', trivia: 'Virtually immune to pests.' },
    { id: 66, g: 'Zamioculcas', n: 'Zamioculcas zamiifolia \'Raven\'', feat: 'The Raven ZZ is a stunning patented cultivar where the new growth emerges a shocking, bright lime green before slowly and dramatically turning a glossy, pitch black. It is a stunning, gothic architectural plant that requires almost zero maintenance to look pristine. Foliage turns black as it matures.', lvl: 'Beginner', origin: 'Cultivar', habitat: 'Indoor Cultivation', trivia: 'Foliage turns black as it matures.', ppfd: 200, ec: 1.4 },
    { id: 67, g: 'Strelitzia', n: 'Strelitzia nicolai (Non-Aroid)', feat: 'The Giant White Bird of Paradise. Brings an instant, massive tropical scale to any space with its huge, paddle-like banana leaves that naturally split to let wind pass through. It requires immense amounts of full sun, heavy watering, and large spaces to thrive and potentially bloom indoors. Can reach ceiling height quickly.', lvl: 'Advanced', origin: 'South Africa', habitat: 'Coastal dunes', trivia: 'Can reach ceiling height quickly.' },
    { id: 68, g: 'Strelitzia', n: 'Strelitzia reginae (Non-Aroid)', feat: 'The classic Bird of Paradise, famous for its incredible, highly complex orange and blue flowers that look exactly like crested tropical birds. It is significantly smaller and slower growing than the Nicolai, making it an excellent, highly structural plant for bright, sunny indoor spaces. Produces bird-shaped orange flowers.', lvl: 'Advanced', origin: 'South Africa', habitat: 'Riverbanks/Coastal Scrub', trivia: 'Produces bird-shaped orange flowers.' },
    { id: 53, g: 'Other', n: 'Stromanthe thalia \'Triostar\'', feat: 'A spectacular prayer plant featuring long, lanceolate leaves boldly striped with white and green. Its highly vibrant, magenta-pink undersides are dramatically revealed at night when the plant undergoes nyctinasty, folding its leaves entirely upright like hands in prayer. Stunning pink leaf undersides.', lvl: 'Advanced', origin: 'Brazil', habitat: 'Humid Forest Floor', trivia: 'Stunning pink leaf undersides.' },
    { id: 54, g: 'Other', n: 'Scindapsus treubii \'Moonlight\'', feat: 'A silvery, highly shimmering aroid that climbs tree trunks in its native Southeast Asian rainforests. Its thick, rigid leaves have a ghostly, metallic appearance that is highly prized by collectors. The silver coloration is a structural adaptation that reflects excess light in the dappled understory. Ghostly silver leaf sheen.', lvl: 'Advanced', origin: 'Southeast Asia', habitat: 'Tropical Rainforest Canopy', trivia: 'Ghostly silver leaf sheen.' },
    { id: 56, g: 'Other', n: 'Begonia chlorosticta (Non-Aroid)', feat: 'An incredibly exotic, notoriously difficult terrarium begonia. It features striking neon green polka dots on a very dark red, almost black base leaf. It looks completely artificial and absolutely requires extremely high humidity (80%+) and terrarium conditions to survive outside of the Malaysian limestone crevices. Neon green dots are characteristic.', lvl: 'Expert', origin: 'Malaysia', habitat: 'Limestone Crevices', trivia: 'Neon green dots are characteristic.' },
    { id: 71, g: 'Rhaphidophora', n: 'Rhaphidophora tetrasperma', feat: 'Known as the "Mini Monstera", it is entirely unrelated to Monsteras but looks like a miniaturized version. It is an incredibly aggressive, fast-growing climber from Southeast Asia that deeply fenestrates early in its lifecycle. Extremely fast climber.', lvl: 'Beginner', origin: 'Southeast Asia', habitat: 'Rainforest Canopy', trivia: 'Extremely fast climber.' },
    { id: 72, g: 'Rhaphidophora', n: 'Rhaphidophora decursiva', feat: 'A robust, massive climbing aroid that starts with solid, entire leaves and slowly develops incredibly deep, palm-like pinnate lobes as it scales high into the canopy. Deeply lobed mature leaves.', lvl: 'Advanced', origin: 'Southeast Asia', habitat: 'Tropical Forest', trivia: 'Deeply lobed mature leaves.' },
    { id: 73, g: 'Scindapsus', n: 'Scindapsus pictus \'Exotica\'', feat: 'The Silver Vine. Known for massive, asymmetrical leaves heavily splashed with shimmering, metallic silver. The silver blister variegation reflects light in the dark understory. It communicates thirst by dramatically curling its leaves inward. Leaves curl when thirsty.', lvl: 'Beginner+', origin: 'Southeast Asia', habitat: 'Jungle Understory', trivia: 'Leaves curl when thirsty.' },
    { id: 74, g: 'Scindapsus', n: 'Scindapsus pictus \'Argyraeus\'', feat: 'A smaller, more delicate version of the Pictus, featuring dark green leaves cleanly edged in silver and delicately speckled with silver dots. A perfect trailing plant for beginners. Silver edges and speckles.', lvl: 'Beginner', origin: 'Southeast Asia', habitat: 'Jungle Understory', trivia: 'Silver edges and speckles.' },
    { id: 75, g: 'Aglaonema', n: 'Aglaonema \'Silver Bay\'', feat: 'The Chinese Evergreen is practically bulletproof. The Silver Bay features sweeping brushstrokes of light silver over dark green. It can survive in extremely low light, making it a staple of interior landscaping. Thrives in very low light.', lvl: 'Beginner', origin: 'Cultivar', habitat: 'Indoor Environment', trivia: 'Thrives in very low light.' },
    { id: 76, g: 'Aglaonema', n: 'Aglaonema \'Crete\'', feat: 'A stunning red Aglaonema cultivar. Its foliage is vividly outlined and striped with bright magenta and red. While older Aglaonemas required low light, these highly colored red cultivars need significantly more light to maintain their intense hues. Red edges require bright light.', lvl: 'Beginner+', origin: 'Cultivar', habitat: 'Indoor Environment', trivia: 'Red edges require bright light.' },
    { id: 77, g: 'Spathiphyllum', n: 'Spathiphyllum wallisii', feat: 'The classic Peace Lily. Native to Central America, it is one of the few indoor plants that reliably "blooms" in low light, producing striking white spathes. It is famous for aggressively drooping when dry, then resurrecting completely an hour after watering. Faints dramatically when dry.', lvl: 'Beginner', origin: 'Central/South America', habitat: 'Rainforest Floor', trivia: 'Faints dramatically when dry.' },
    { id: 78, g: 'Philodendron', n: 'Philodendron spiritus-sancti', feat: 'The holy grail of Philodendrons, saved from extinction by tissue culture. Native to Espírito Santo, Brazil, it features long, pendulous sword-shaped leaves. Extremely demanding, requiring high airflow to mimic its native windy cliffs.', lvl: 'Expert', origin: 'Brazil', habitat: 'Highland Cliffs', trivia: 'Saved from extinction by tissue culture.', ppfd: 90, ec: 1.2 },
    { id: 79, g: 'Other', n: 'Amorphophallus titanum', feat: 'The Corpse Flower. Produces a massive, thermogenic spadix that smells like decaying meat to attract specialized carrion beetles. It undergoes a single massive leaf cycle before blooming.', lvl: 'Expert', origin: 'Sumatra', habitat: 'Tropical Rainforest', trivia: 'Produces a massive thermogenic inflorescence.', ppfd: 400, ec: 2.8 },
    { id: 80, g: 'Anthurium', n: 'Anthurium warocqueanum', feat: 'The Queen Anthurium. Known for its incredibly long, dark velvet leaves that can reach several feet in length. Its roots require aggressive air-pruning and are highly sensitive to salt buildup.', lvl: 'Expert', origin: 'Colombia', habitat: 'Chocó Cloud Forest', trivia: 'Roots are highly sensitive to salt buildup.', ppfd: 130, ec: 1.2 },
    { id: 81, g: 'Alocasia', n: 'Alocasia \'Jacklyn\' Albo', feat: 'A highly rare mutation of the recently discovered Alocasia Jacklyn. Features stark white, ghostly sectors on deeply lobed, hairy leaves. It is an extremely rare collector\'s item.', lvl: 'Expert', origin: 'Sulawesi Origin', habitat: 'Montane Forest', trivia: 'Stark white ghost sectors on hairy leaves.', ppfd: 150, ec: 2.2 },
    { id: 82, g: 'Alocasia', n: 'Alocasia melo', feat: 'The Stone Leaf Alocasia. Its incredibly stiff leaves feel exactly like thick, textured plastic or carved stone. Native to the ultramafic soils of Borneo.', lvl: 'Advanced', origin: 'Borneo', habitat: 'Ultramafic Soils', trivia: 'Leaves feel like thick textured plastic.', ppfd: 60, ec: 1.6 },
    { id: 83, g: 'Philodendron', n: 'Philodendron melanochrysum', feat: 'The Black Gold Philodendron. Its massive, velvety black-green leaves are adorned with shimmering gold veins. It requires high humidity to unfurl properly and needs vertical hydro-support to reach mature sizes.', lvl: 'Advanced', origin: 'Colombia', habitat: 'Andean Cloud Forest', trivia: 'Velvety black-green leaves with gold veins.', ppfd: 80, ec: 1.2 },
    { id: 84, g: 'Anthurium', n: 'Anthurium veitchii \'King\'', feat: 'The King Anthurium. Famous for its deeply corrugated, pendulous leaves that can reach up to 6 feet in length. High light intensity significantly deepens the incredible ribbing texture.', lvl: 'Expert', origin: 'Colombia', habitat: 'Andean Foothills', trivia: 'High light deepens the corrugated texture.', ppfd: 250, ec: 1.6 },
    { id: 85, g: 'Philodendron', n: 'Philodendron gloriosum \'White Vein\'', feat: 'A terrestrial crawler with shimmering silver and white venation across large, heart-shaped velvety leaves. Its rhizome must be planted horizontally across the surface of the soil to prevent rot.', lvl: 'Advanced', origin: 'Colombia', habitat: 'Understory Floor', trivia: 'Terrestrial crawler with silver/white veins.', ppfd: 100, ec: 1.4 },
    { id: 86, g: 'Philodendron', n: 'Philodendron \'Florida Ghost\'', feat: 'A remarkable hybrid where new leaves emerge entirely ghost-white, slowly fading to mint and eventually a solid green as they harden. This fascinating color shift requires bright light to express properly.', lvl: 'Advanced', origin: 'Florida Hybrid', habitat: 'Lowland Origin', trivia: 'Leaves emerge entirely ghost-white.', ppfd: 160, ec: 1.6 },
    { id: 87, g: 'Alocasia', n: 'Alocasia frydek \'Variegata\'', feat: 'A highly sought-after variegated form of the Alocasia micholitziana. Features velvety, dark green leaves with stark, contrasting white to cream chimeric variegation. It is notoriously finicky and requires very stable conditions to prevent the white sectors from crisping.', lvl: 'Expert', origin: 'Cultivation Mutation', habitat: 'Tropical Cultivation', trivia: 'Highly unstable variegation.' },
    { id: 88, g: 'Anthurium', n: 'Anthurium clarinervium', feat: 'A stunning Mexican Anthurium famous for its deep green, velvety, heart-shaped leaves prominently adorned with brilliant white, crystalline veins. It remains relatively compact, making it a perfect jewel for aroid collectors.', lvl: 'Advanced', origin: 'Mexico', habitat: 'Limestone Outcrops', trivia: 'Features stark white crystalline veins.' },
    { id: 89, g: 'Anthurium', n: 'Anthurium crystallinum', feat: 'Similar to clarinervium but capable of growing much larger, this species features massive, velvety leaves with striking silver veins that glitter like crystals under light.', lvl: 'Advanced', origin: 'Central to South America', habitat: 'Rainforest Margins', trivia: 'Veins glitter like crystals under light.' },
    { id: 90, g: 'Anthurium', n: 'Anthurium forgetii', feat: 'A unique Anthurium easily distinguished by its lack of a sinus (the deep cleft at the top of the leaf). Its completely closed, peltate, velvety leaves are accented by beautiful silver venation.', lvl: 'Advanced', origin: 'Colombia', habitat: 'Wet Tropical Forest', trivia: 'Lacks the typical upper leaf sinus.' },
    { id: 91, g: 'Anthurium', n: 'Anthurium luxurians', feat: 'An incredibly textured species with leaves that look and feel like hammered metal or reptilian skin. It grows slowly but develops deeply bullate (puckered) leaves that capture light dramatically.', lvl: 'Expert', origin: 'Colombia', habitat: 'Rainforest Understory', trivia: 'Leaves resemble deeply hammered metal.' },
    { id: 92, g: 'Anthurium', n: 'Anthurium regale', feat: 'A massive, regal species that can produce leaves stretching several feet wide. The sheer scale of its velvety foliage crisscrossed with luminous pale green veins demands high humidity and immense space.', lvl: 'Expert', origin: 'Peru', habitat: 'Cloud Forest Floor', trivia: 'Leaves can reach several feet wide.' },
    { id: 93, g: 'Anthurium', n: 'Anthurium veitchii', feat: 'The King Anthurium. Unlike the compact "King" cultivar, the standard species exhibits the iconic elongated, heavily corrugated leaves that hang pendulously from the forest canopy.', lvl: 'Expert', origin: 'Colombia', habitat: 'Andean Foothills', trivia: 'Features long, heavily corrugated leaves.' },
    { id: 94, g: 'Anthurium', n: 'Anthurium vittarifolium', feat: 'A spectacular pendant (hanging) Anthurium that produces extremely long, slender, strap-like leaves. It requires a hanging basket and high humidity to let its foliage cascade elegantly downwards.', lvl: 'Advanced', origin: 'South America', habitat: 'Epiphytic Rainforest Canopy', trivia: 'Extremely long, strap-like pendant leaves.' },
    { id: 95, g: 'Philodendron', n: 'Philodendron billietiae', feat: 'A dramatic, highly structural Philodendron known for its long, rigid, arrow-shaped leaves and incredibly striking, bright neon-orange petioles (stems).', lvl: 'Advanced', origin: 'French Guiana/Brazil', habitat: 'Lowland Rainforest Canopy', trivia: 'Features striking bright orange petioles.' },
    { id: 96, g: 'Philodendron', n: 'Philodendron gloriosum', feat: 'A magnificent terrestrial crawler with massive, heart-shaped, velvety green leaves. Unlike the White Vein cultivar, it typically features pale green or slightly pinkish venation that fades into the rich foliage.', lvl: 'Advanced', origin: 'Colombia', habitat: 'Understory Floor', trivia: 'Terrestrial crawler with velvety leaves.' },
    { id: 97, g: 'Philodendron', n: 'Philodendron tortum', feat: 'An incredibly unique Philodendron with deeply cut, almost skeletal leaves that closely resemble a palm frond. As it matures, it becomes a chaotic, twisting, sprawling jungle vine.', lvl: 'Advanced', origin: 'Brazil', habitat: 'Tropical Forest Canopy', trivia: 'Leaves resemble skeletal palm fronds.' },
    { id: 98, g: 'Philodendron', n: 'Philodendron verrucosum', feat: 'A true rainforest jewel. Its stunning, velvety dark green leaves are complemented by bright red undersides and petioles densely covered in fuzzy, hair-like bristles (pubescence).', lvl: 'Expert', origin: 'Central to South America', habitat: 'Montane Cloud Forest', trivia: 'Features fuzzy, bristly petioles.' },
    { id: 99, g: 'Philodendron', n: 'Philodendron \'Jose Buono\'', feat: 'A spectacular variegated Philodendron featuring massive, paddle-shaped leaves heavily splashed with bright, stable white and cream variegation that does not easily revert.', lvl: 'Advanced', origin: 'Cultivar', habitat: 'Tropical Cultivation', trivia: 'Stable white and cream splashed variegation.' },
    { id: 100, g: 'Philodendron', n: 'Philodendron \'White Princess\'', feat: 'A compact, self-heading variegated hybrid featuring vibrant green leaves splashed with stark white and occasional pink hues. Its stems typically exhibit striking pink and green striping.', lvl: 'Advanced', origin: 'Cultivar', habitat: 'Tropical Cultivation', trivia: 'Stems exhibit pink and green striping.' },
    { id: 101, g: 'Philodendron', n: 'Philodendron \'White Wizard\'', feat: 'A fast-growing climbing Philodendron known for large, rounded leaves with crisp white variegation. Unlike the White Princess, its stems are entirely green and white without any pink tones.', lvl: 'Advanced', origin: 'Cultivar', habitat: 'Tropical Cultivation', trivia: 'Climber with pure green and white stems.' },
    { id: 102, g: 'Philodendron', n: 'Philodendron billietiae \'Variegata\'', feat: 'An incredibly rare and expensive mutation of the P. billietiae. It combines the species\' signature orange petioles with breathtaking, high-contrast yellow and cream variegation across its arrow-shaped leaves.', lvl: 'Expert', origin: 'Cultivation Mutation', habitat: 'Tropical Cultivation', trivia: 'Rare orange petioles and yellow variegation.' }
];
